---

user_state: "{{ crc_state }}"
user_groups:
  - name: crcug
  - name: traefikug
  - name: traefikugs
  - name: traefikugl
  - name: traefikugal
user_users:
  - name: crcuo
    group: crcug
    groups: adm,sys,wheel,kvm,libvirt
    create_home: true
    systemd: true
  - name: traefikuo
    group: traefikug
    create_home: true
  - name: traefikuos
    group: traefikugs
    create_home: true
    groups: traefikugl
    systemd: true
  - name: traefikual
    group: traefikugal
    groups: traefikugl

package_state: "{{ crc_state }}"
package_packages:
  - {package: iptables-services}
  - {package: libvirt}
  - {package: libvirt-daemon-kvm}
  - {package: qemu-kvm}
  - {package: NetworkManager}
  - {package: jq}

crc_state: present
crc_user_owner: crcuo
crc_user_group: crcug
crc_version: 2.34.1
crc_ocp_version: 4.15.9
crc_config_pull_secret_file: "{{ vault_crc_pull_secret }}"
crc_config_cpus: 6
crc_config_memory: 12288
